import crypto from 'node:crypto';
import axios from 'axios';
import { getPrisma } from '../../research/prisma.js';

const CATEGORIES=['geopolitics','central-bank-policy','industry-policy','economic-data'];
const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
const strip=value=>String(value||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const status=(source,url,fetchedAt,state,extra={})=>({source,url,status:state,fetchedAt:fetchedAt.toISOString(),...extra});
let activeRefresh=null;

export function majorCategory(text){const value=String(text).toLowerCase();if(/war|sanction|tariff|geopolit|conflict|战争|制裁|关税|地缘/.test(value))return'geopolitics';if(/central bank|pboc|federal reserve|interest rate|ecb|央行|人民银行|美联储|利率/.test(value))return'central-bank-policy';if(/regulation|subsidy|industry policy|industrial policy|监管|补贴|产业政策/.test(value))return'industry-policy';return'economic-data';}
function gdeltDate(value){const m=String(value||'').match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?/);return m?new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]||'00'}:${m[5]||'00'}:00Z`):null;}
function rssItems(xml){return [...String(xml).matchAll(/<item\b[\s\S]*?<\/item>/gi)].map(match=>{const item=match[0],field=name=>strip(item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]);return{title:field('title'),url:field('link'),summary:field('description'),publishedAt:new Date(field('pubDate')||field('dc:date'))};}).filter(x=>x.title&&x.url&&!Number.isNaN(x.publishedAt.getTime()));}
async function persist(db,row,fetchedAt){const canonicalKey=hash(row.url);return db.majorFinancialEvent.upsert({where:{canonicalKey},create:{canonicalKey,category:row.category||majorCategory(`${row.title} ${row.summary||''}`),title:row.title,summary:row.summary||null,publishedAt:row.publishedAt||fetchedAt,sourceName:row.sourceName,sourceUrl:row.sourceUrl,articleUrl:row.url,fetchedAt,retrievalStatus:'live',raw:row.raw||{}},update:{category:row.category||majorCategory(`${row.title} ${row.summary||''}`),title:row.title,summary:row.summary||null,publishedAt:row.publishedAt||fetchedAt,sourceName:row.sourceName,sourceUrl:row.sourceUrl,articleUrl:row.url,fetchedAt,retrievalStatus:'live',raw:row.raw||{}}});}

async function gdelt(db,fetchedAt){const endpoint='https://api.gdeltproject.org/api/v2/doc/doc',query='(geopolitics OR sanctions OR war OR tariff OR "central bank" OR PBOC OR "Federal Reserve" OR regulation OR subsidy OR GDP OR CPI OR PMI OR unemployment) economy finance';const {data}=await axios.get(endpoint,{params:{query,mode:'ArtList',maxrecords:50,format:'json',sort:'HybridRel'},timeout:Number(process.env.NEWS_HTTP_TIMEOUT_MS||15000),headers:{'User-Agent':process.env.FINANCE_USER_AGENT||'ai-research-platform/1.0'}});const rows=Array.isArray(data?.articles)?data.articles:[];if(!rows.length)throw new Error('empty response');const events=[];for(const row of rows){if(row.url&&row.title)events.push(await persist(db,{title:row.title,url:row.url,publishedAt:gdeltDate(row.seendate)||fetchedAt,sourceName:row.domain||'GDELT indexed publisher',sourceUrl:endpoint,raw:row},fetchedAt));}return{events,state:status('GDELT 2.1 DOC API',endpoint,fetchedAt,'live',{count:events.length})};}

const RSS_SOURCES=[
  {source:'Federal Reserve',url:'https://www.federalreserve.gov/feeds/press_all.xml',category:'central-bank-policy'},
  {source:'ECB',url:'https://www.ecb.europa.eu/rss/press.html',category:'central-bank-policy'},
  {source:'IMF',url:'https://www.imf.org/en/News/RSS',category:'economic-data'},
  {source:'Google 新闻·地缘政治（中文）',url:'https://news.google.com/rss/search?q=%E5%9C%B0%E7%BC%98%E6%94%BF%E6%B2%BB%20OR%20%E5%88%B6%E8%A3%81%20OR%20%E5%85%B3%E7%A8%8E%20OR%20%E6%88%98%E4%BA%89%20%E7%BB%8F%E6%B5%8E&hl=zh-CN&gl=CN&ceid=CN:zh-Hans',category:'geopolitics'},
  {source:'Google 新闻·央行政策（中文）',url:'https://news.google.com/rss/search?q=%E5%A4%AE%E8%A1%8C%20OR%20%E4%BA%BA%E6%B0%91%E9%93%B6%E8%A1%8C%20OR%20%E7%BE%8E%E8%81%94%E5%82%A8%20OR%20%E5%88%A9%E7%8E%87&hl=zh-CN&gl=CN&ceid=CN:zh-Hans',category:'central-bank-policy'},
  {source:'Google 新闻·行业政策（中文）',url:'https://news.google.com/rss/search?q=%E4%BA%A7%E4%B8%9A%E6%94%BF%E7%AD%96%20OR%20%E8%A1%8C%E4%B8%9A%E7%9B%91%E7%AE%A1%20OR%20%E8%A1%A5%E8%B4%B4&hl=zh-CN&gl=CN&ceid=CN:zh-Hans',category:'industry-policy'},
  {source:'Google 新闻·经济数据（中文）',url:'https://news.google.com/rss/search?q=GDP%20OR%20CPI%20OR%20PMI%20OR%20%E5%A4%B1%E4%B8%9A%E7%8E%87%20%E7%BB%8F%E6%B5%8E&hl=zh-CN&gl=CN&ceid=CN:zh-Hans',category:'economic-data'},
  {source:'Google News 地缘政治',url:'https://news.google.com/rss/search?q=geopolitics%20OR%20sanctions%20OR%20tariff%20OR%20war%20economy&hl=en-US&gl=US&ceid=US:en',category:'geopolitics'},
  {source:'Google News 行业政策',url:'https://news.google.com/rss/search?q=industry%20policy%20OR%20regulation%20OR%20subsidy%20economy&hl=en-US&gl=US&ceid=US:en',category:'industry-policy'},
  {source:'Google News 经济数据',url:'https://news.google.com/rss/search?q=GDP%20OR%20CPI%20OR%20PMI%20OR%20unemployment%20economy&hl=en-US&gl=US&ceid=US:en',category:'economic-data'}
];
async function rssSource(db,spec,fetchedAt){const {data}=await axios.get(spec.url,{timeout:Number(process.env.NEWS_HTTP_TIMEOUT_MS||15000),responseType:'text',headers:{'User-Agent':process.env.FINANCE_USER_AGENT||'ai-research-platform/1.0'}});const rows=rssItems(data).slice(0,30),events=[];if(!rows.length)throw new Error('empty RSS response');for(const row of rows)events.push(await persist(db,{...row,category:spec.category,sourceName:spec.source,sourceUrl:spec.url,raw:{feed:spec.url}},fetchedAt));return{events,state:status(spec.source,spec.url,fetchedAt,'live',{count:events.length})};}

async function refresh(){const db=getPrisma(),fetchedAt=new Date(),statuses=[],events=[];const collectors=[()=>gdelt(db,fetchedAt),...RSS_SOURCES.map(spec=>()=>rssSource(db,spec,fetchedAt))];const settled=await Promise.allSettled(collectors.map(run=>run()));settled.forEach((result,index)=>{if(result.status==='fulfilled'){events.push(...result.value.events);statuses.push(result.value.state);}else{const spec=index===0?{source:'GDELT 2.1 DOC API',url:'https://api.gdeltproject.org/api/v2/doc/doc'}:RSS_SOURCES[index-1];statuses.push(status(spec.source,spec.url,fetchedAt,'degraded',{error:result.reason?.message||'fetch failed'}));}});
 const unique=[...new Map(events.map(event=>[String(event.id),event])).values()];const coverage=Object.fromEntries(CATEGORIES.map(category=>[category,unique.filter(event=>event.category===category).length]));
 if(!unique.length){const cached=await db.majorFinancialEvent.findMany({take:80,orderBy:{publishedAt:'desc'}});statuses.push(status('PostgreSQL event cache','database://major_financial_events',fetchedAt,cached.length?'stale':'unavailable',{count:cached.length}));return{events:cached,statuses,coverage:Object.fromEntries(CATEGORIES.map(category=>[category,cached.filter(x=>x.category===category).length])),fetchedAt:fetchedAt.toISOString(),status:cached.length?'degraded':'unavailable'};}
 return{events:unique.sort((a,b)=>b.publishedAt-a.publishedAt).slice(0,80),statuses,coverage,fetchedAt:fetchedAt.toISOString(),status:statuses.some(x=>x.status==='live')?'live':'degraded'};
}
export function collectMajorEvents(){if(!activeRefresh)activeRefresh=refresh().finally(()=>{activeRefresh=null;});return activeRefresh;}
export async function listMajorEvents({limit=50,category}={}){const db=getPrisma(),requested=Math.min(200,Math.max(1,limit)),rows=await db.majorFinancialEvent.findMany({where:category?{category}:undefined,take:200,orderBy:{publishedAt:'desc'}}),isChinese=item=>/[\u4e00-\u9fff]/.test(`${item.title||''} ${item.summary||''}`),isLowQuality=item=>/怎么选|购买指南|补贴攻略|FAQ|哪款|测评|推荐清单|直播带货/i.test(item.title||''),items=rows.filter(item=>!isLowQuality(item)).sort((a,b)=>Number(isChinese(b))-Number(isChinese(a))||b.publishedAt-a.publishedAt).slice(0,requested).map(item=>({...item,originalLanguage:isChinese(item)?'zh':'en',summaryZh:isChinese(item)?strip(item.summary)||item.title:null})),fetchedAt=items.reduce((latest,x)=>x.fetchedAt>latest?x.fetchedAt:latest,new Date(0)),coverage=Object.fromEntries(CATEGORIES.map(key=>[key,items.filter(x=>x.category===key).length]));return{events:items,status:items.length?'cached':'unavailable',fetchedAt:items.length?fetchedAt.toISOString():null,coverage,source:[...new Set(items.map(x=>x.sourceName))]};}
