import crypto from 'crypto';
import { transaction, query } from './db.js';
import { fetchArxiv } from './providers/arxiv.js';
import { fetchSemanticScholar } from './providers/semantic-scholar.js';
import { fetchOpenAlex } from './providers/openalex.js';
import { fetchHuggingFace } from './providers/huggingface.js';
const key = (prefix, value) => `${prefix}:${String(value).trim().toLowerCase()}`;
const hash = value => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function provenance(c,type,id,item) { await c.query(`INSERT INTO provenance(entity_type,entity_id,provider,provider_id,source_url,payload_hash,fetched_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(entity_type,provider,provider_id) DO UPDATE SET entity_id=excluded.entity_id,source_url=excluded.source_url,payload_hash=excluded.payload_hash,fetched_at=now()`,[type,id,item.provider,item.providerId,item.sourceUrl,hash(item.raw||item)]); }
async function upsertPaper(c,p) {
 const canonical=p.doi?key('doi',p.doi):key(p.provider,p.providerId); const r=await c.query(`INSERT INTO papers(canonical_key,title,abstract,publication_date,venue,doi,citation_count,concepts,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(canonical_key) DO UPDATE SET title=excluded.title,abstract=COALESCE(excluded.abstract,papers.abstract),publication_date=COALESCE(excluded.publication_date,papers.publication_date),venue=COALESCE(excluded.venue,papers.venue),citation_count=GREATEST(papers.citation_count,excluded.citation_count),concepts=excluded.concepts,raw=excluded.raw,updated_at=now() RETURNING id`,[canonical,p.title,p.abstract||null,p.publicationDate||null,p.venue||null,p.doi||null,p.citationCount||0,JSON.stringify(p.topics||[]),JSON.stringify(p.raw||{})]); const id=r.rows[0].id; await provenance(c,'paper',id,p);
 for (const [position,a] of (p.authors||[]).entries()) { const ak=a.providerId?key(p.provider,a.providerId):key('name',a.name); const ar=await c.query(`INSERT INTO authors(canonical_key,name,affiliations,raw) VALUES($1,$2,$3,$4) ON CONFLICT(canonical_key) DO UPDATE SET name=excluded.name,affiliations=excluded.affiliations,updated_at=now() RETURNING id`,[ak,a.name,JSON.stringify(a.affiliations||[]),JSON.stringify(a)]); await c.query('INSERT INTO paper_authors VALUES($1,$2,$3) ON CONFLICT(paper_id,author_id) DO UPDATE SET position=excluded.position',[id,ar.rows[0].id,position]); }
 for (const t of p.topics||[]) { const tk=t.providerId?key(p.provider,t.providerId):key('name',t.name); const tr=await c.query(`INSERT INTO topics(canonical_key,name,raw) VALUES($1,$2,$3) ON CONFLICT(canonical_key) DO UPDATE SET name=excluded.name,raw=excluded.raw,updated_at=now() RETURNING id`,[tk,t.name,JSON.stringify(t)]); await c.query('INSERT INTO paper_topics VALUES($1,$2,$3) ON CONFLICT(paper_id,topic_id) DO UPDATE SET score=excluded.score',[id,tr.rows[0].id,t.score||null]); }
 for (const ref of p.references||[]) await c.query(`INSERT INTO citations(citing_paper_id,cited_paper_id,source) SELECT $1,entity_id,$2 FROM provenance WHERE entity_type='paper' AND provider=$2 AND provider_id=$3 ON CONFLICT DO NOTHING`,[id,p.provider,ref]); return id;
}
async function upsertModel(c,m) { const r=await c.query(`INSERT INTO models(canonical_key,name,author_name,pipeline_tag,downloads,likes,tags,last_modified,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(canonical_key) DO UPDATE SET name=excluded.name,author_name=excluded.author_name,pipeline_tag=excluded.pipeline_tag,downloads=excluded.downloads,likes=excluded.likes,tags=excluded.tags,last_modified=excluded.last_modified,raw=excluded.raw,updated_at=now() RETURNING id`,[key(m.provider,m.providerId),m.name,m.authorName,m.pipelineTag,m.downloads||0,m.likes||0,JSON.stringify(m.tags),m.lastModified||null,JSON.stringify(m.raw)]); await provenance(c,'model',r.rows[0].id,m); }
export async function ingest(provider,opts={}) { const run=await query('INSERT INTO ingestion_runs(provider,query) VALUES($1,$2) RETURNING id',[provider,opts.query||null]); try { let result; if(provider==='arxiv') result=await fetchArxiv(opts); else if(provider==='semantic-scholar') result=await fetchSemanticScholar(opts); else if(provider==='openalex') result=(await fetchOpenAlex(opts)).items; else if(provider==='huggingface') result=await fetchHuggingFace(opts); else throw Object.assign(new Error(`Unknown provider: ${provider}`),{status:400,code:'INVALID_PROVIDER'}); await transaction(async c=>{for(const item of result) provider==='huggingface'?await upsertModel(c,item):await upsertPaper(c,item);}); await query("UPDATE ingestion_runs SET status='succeeded',records=$2,finished_at=now() WHERE id=$1",[run.rows[0].id,result.length]); return {runId:run.rows[0].id,provider,records:result.length}; } catch(e) { await query("UPDATE ingestion_runs SET status='failed',error=$2,finished_at=now() WHERE id=$1",[run.rows[0].id,e.message]).catch(()=>{}); throw e; } }
