import { getPrisma } from '../../research/prisma.js';
import { cleanCode, marketFor } from '../normalize.js';

export const ownerKey = req => { const key=String(req.get('x-owner-key')||'').trim(); if(!key)throw Object.assign(new Error('X-Owner-Key header is required'),{status:401,code:'OWNER_REQUIRED'}); return key.slice(0,128); };
const n=value=>Number(value||0);
export async function getPortfolio(id,owner){const db=getPrisma();const portfolio=await db.portfolio.findFirst({where:{id:BigInt(id),ownerKey:owner},include:{holdings:{include:{stock:{include:{industry:true,prices:{take:1,orderBy:{tradeDate:'desc'},include:{source:true}},statements:{take:1,orderBy:{periodEnd:'desc'},include:{source:true}},news:{take:5,orderBy:{publishedAt:'desc'},include:{source:true}}}}}}}});if(!portfolio)throw Object.assign(new Error('Portfolio not found'),{status:404,code:'PORTFOLIO_NOT_FOUND'});return portfolio;}
export async function upsertHolding(portfolioId,owner,input,source='manual'){const db=getPrisma(),portfolio=await db.portfolio.findFirst({where:{id:BigInt(portfolioId),ownerKey:owner}});if(!portfolio)throw Object.assign(new Error('Portfolio not found'),{status:404});const databaseCode=cleanCode(input.stockCode),stockCode=`${databaseCode}.${marketFor(databaseCode)}`,stock=await db.stock.findUnique({where:{code:databaseCode},include:{prices:{take:1,orderBy:{tradeDate:'desc'}}}});if(!stock)throw Object.assign(new Error(`Stock ${stockCode} not found in real market database`),{status:422,code:'STOCK_NOT_INDEXED'});const shares=n(input.shares),costPrice=n(input.costPrice);if(!(shares>0)||!(costPrice>=0))throw Object.assign(new Error('shares must be > 0 and costPrice >= 0'),{status:400});const currentValue=shares*n(stock.prices[0]?.close);return db.portfolioHolding.upsert({where:{portfolioId_stockId:{portfolioId:portfolio.id,stockId:stock.id}},create:{portfolioId:portfolio.id,stockId:stock.id,stockCode,shares,costPrice,buyDate:input.buyDate?new Date(input.buyDate):null,currentValue,source,raw:input},update:{stockCode,shares,costPrice,buyDate:input.buyDate?new Date(input.buyDate):null,currentValue,source,raw:input}});}
export async function analyzePortfolio(id,owner){const db=getPrisma(),portfolio=await getPortfolio(id,owner);let totalValue=0,totalCost=0;const holdings=portfolio.holdings.map(h=>{const price=h.stock.prices[0],current=n(price?.close),value=n(h.shares)*current,cost=n(h.shares)*n(h.costPrice),pnl=value-cost,pnlPct=cost?pnl/cost:0;totalValue+=value;totalCost+=cost;return{holding:h,current,value,cost,pnl,pnlPct,price};});const industryMap=new Map();for(const x of holdings){const name=x.holding.stock.industry?.name||'未分类';industryMap.set(name,(industryMap.get(name)||0)+x.value);}const citations=[];for(const x of holdings){if(x.price)citations.push({type:'stock_price',id:String(x.price.id),title:`${x.holding.stock.name} 最新行情`,url:x.price.sourceUrl,data:{close:String(x.price.close),changePercent:x.price.changePercent&&String(x.price.changePercent),fetchedAt:x.price.fetchedAt}});const f=x.holding.stock.statements[0];if(f)citations.push({type:'financial_statement',id:String(f.id),title:`${x.holding.stock.name} 财务指标`,url:f.sourceUrl,data:{roe:f.roe&&String(f.roe),netProfit:f.netProfit&&String(f.netProfit)}});for(const article of x.holding.stock.news.slice(0,2))citations.push({type:'news',id:String(article.id),title:article.title,url:article.url,data:{sentiment:article.sentiment&&String(article.sentiment),publishedAt:article.publishedAt}});}
 const maxWeight=totalValue?Math.max(...holdings.map(x=>x.value/totalValue)):0;const negativeNews=holdings.flatMap(x=>x.holding.stock.news).filter(a=>n(a.sentiment)<0).length;const riskScore=Math.min(100,maxWeight*70+negativeNews*5+Math.max(0,-((totalValue-totalCost)/(totalCost||1)))*20);const recommendations=[];for(const x of holdings){const weight=totalValue?x.value/totalValue:0;if(weight>.35)recommendations.push({stockCode:x.holding.stockCode,action:'reduce-concentration',reason:`单一持仓权重 ${(weight*100).toFixed(1)}% 超过 35% 风险阈值`});if(x.holding.stock.news.some(a=>n(a.sentiment)<0))recommendations.push({stockCode:x.holding.stockCode,action:'review-risk',reason:'近期存在负面新闻或公告信号'});}await db.$transaction(holdings.map(x=>db.portfolioHolding.update({where:{id:x.holding.id},data:{currentValue:x.value,weight:totalValue?x.value/totalValue:0}})));
 return{portfolio:{id:String(portfolio.id),name:portfolio.name,currency:portfolio.currency},asOf:new Date(),performance:{totalValue,totalCost,pnl:totalValue-totalCost,pnlPct:totalCost?(totalValue-totalCost)/totalCost:0},risk:{score:riskScore,level:riskScore>65?'high':riskScore>35?'medium':'controlled',maxPositionWeight:maxWeight,negativeNews},industryExposure:[...industryMap].map(([industry,value])=>({industry,value,weight:totalValue?value/totalValue:0})).sort((a,b)=>b.value-a.value),holdings:holdings.map(x=>({stockCode:x.holding.stockCode,name:x.holding.stock.name,shares:n(x.holding.shares),costPrice:n(x.holding.costPrice),currentPrice:n(x.price?.close),currentValue:x.value,weight:totalValue?x.value/totalValue:0,pnl:x.pnl,pnlPct:x.pnlPct,suggestion:recommendations.find(r=>r.stockCode===x.holding.stockCode)||{action:'hold-and-monitor',reason:'当前证据未触发集中度或新闻风险规则'}})),rebalance:recommendations.length?recommendations:[{action:'no-forced-change',reason:'当前真实数据未触发规则化调仓条件'}],citations,disclosure:'基于真实行情、财务和新闻的透明规则分析，不构成投资建议。'};}
