import { getPrisma } from '../../research/prisma.js';
import { TushareProvider } from './tushare.js';

const provider=new TushareProvider();
const date=value=>value?new Date(`${String(value).slice(0,4)}-${String(value).slice(4,6)}-${String(value).slice(6,8)}T00:00:00Z`):null;
const code=tsCode=>String(tsCode||'').split('.')[0].padStart(6,'0');
const number=value=>value==null||value===''?null:Number(value);
async function source(db){return db.dataSource.upsert({where:{key:'tushare'},create:{key:'tushare',name:'Tushare Pro',baseUrl:'https://tushare.pro/',kind:'market-data'},update:{enabled:true}});}
async function run(job,action){const db=getPrisma(),ds=await source(db),run=await db.ingestionRun.create({data:{job,provider:'tushare',sourceId:ds.id}});try{const result=await action(db,ds);await db.ingestionRun.update({where:{id:run.id},data:{status:'succeeded',finishedAt:new Date(),recordsRead:result.read,recordsWritten:result.written,metadata:result}});return result;}catch(error){await db.ingestionRun.update({where:{id:run.id},data:{status:'failed',finishedAt:new Date(),error:error.message}});throw error;}}
export async function ingestTushareBasic(){return run('tushare-basic',async(db)=>{const rows=await provider.stockBasic(),industries=new Map(),written=[];for(const row of rows){let industryId=null;if(row.industry){if(!industries.has(row.industry))industries.set(row.industry,(await db.industry.upsert({where:{code:`tushare:${row.industry}`},create:{code:`tushare:${row.industry}`,name:row.industry,source:'tushare',raw:{}},update:{name:row.industry}})).id);industryId=industries.get(row.industry);}await db.stock.upsert({where:{code:code(row.ts_code)},create:{code:code(row.ts_code),name:row.name,market:row.market||row.exchange,exchange:row.exchange,industryId,listDate:date(row.list_date),raw:row},update:{name:row.name,market:row.market||row.exchange,exchange:row.exchange,industryId,listDate:date(row.list_date),raw:row}});written.push(row.ts_code);}return{read:rows.length,written:written.length};});}
export async function ingestTushareDaily(tradeDate){return run('tushare-daily',async(db,ds)=>{
  const rows=await provider.dailyQuotes({trade_date:tradeDate}),day=date(tradeDate);
  if(!day||!rows.length)return{read:rows.length,written:0,tradeDate};
  const codes=[...new Set(rows.map(row=>code(row.ts_code)))],stocks=await db.stock.findMany({where:{code:{in:codes}},select:{id:true,code:true}}),byCode=new Map(stocks.map(stock=>[stock.code,stock.id]));
  const data=rows.flatMap(row=>{const stockId=byCode.get(code(row.ts_code));if(!stockId)return[];return[{stockId,tradeDate:day,close:number(row.close),open:number(row.open),high:number(row.high),low:number(row.low),previousClose:number(row.pre_close),changePercent:number(row.pct_chg),volume:row.vol==null?null:BigInt(Math.trunc(Number(row.vol)*100)),turnover:number(row.amount)==null?null:number(row.amount)*1000,interval:'1d',sourceId:ds.id,providerKey:`${row.ts_code}:${tradeDate}`,sourceUrl:'https://tushare.pro/',payloadHash:'tushare-api',raw:row}];});
  const result=await db.stockPrice.createMany({data,skipDuplicates:true});
  return{read:rows.length,written:result.count,tradeDate};
});}
export async function ingestTushareFinancials(tsCode){return run('tushare-financials',async(db,ds)=>{const rows=await provider.financialIndicators({ts_code:tsCode}),stock=await db.stock.findUnique({where:{code:code(tsCode)}});if(!stock)throw new Error(`Stock ${tsCode} not found`);let written=0;for(const row of rows){const periodEnd=date(row.end_date);if(!periodEnd)continue;await db.financialStatement.upsert({where:{stockId_statementType_periodEnd_sourceId:{stockId:stock.id,statementType:'financial-indicator',periodEnd,sourceId:ds.id}},create:{stockId:stock.id,statementType:'financial-indicator',periodEnd,roe:number(row.roe),grossMargin:number(row.grossprofit_margin),metrics:row,sourceId:ds.id,providerKey:`${tsCode}:${row.end_date}`,sourceUrl:'https://tushare.pro/',payloadHash:'tushare-api',raw:row},update:{roe:number(row.roe),grossMargin:number(row.grossprofit_margin),metrics:row,fetchedAt:new Date(),raw:row}});written++;}return{read:rows.length,written};});}
export async function ingestTushareTopList(tradeDate){return run('tushare-top-list',async(db,ds)=>{const rows=await provider.topList({trade_date:tradeDate}),day=date(tradeDate);let written=0;for(const row of rows){const stock=await db.stock.findUnique({where:{code:code(row.ts_code)}}),providerKey=`${row.ts_code}:${row.reason||''}`;await db.dragonTigerEntry.upsert({where:{tradeDate_providerKey_sourceId:{tradeDate:day,providerKey,sourceId:ds.id}},create:{stockId:stock?.id,tradeDate:day,reason:row.reason,close:number(row.close),changePercent:number(row.pct_change),turnoverRate:number(row.turnover_rate),amount:number(row.amount),netAmount:number(row.net_amount),sourceId:ds.id,providerKey,raw:row},update:{stockId:stock?.id,reason:row.reason,netAmount:number(row.net_amount),fetchedAt:new Date(),raw:row}});written++;}return{read:rows.length,written};});}
