import { Router } from 'express';
import { getPrisma } from '../research/prisma.js';
import { TushareProvider } from './providers/tushare.js';

const dateKey=d=>d.toISOString().slice(0,10).replaceAll('-','');
const num=v=>v==null?null:Number(v);
function stageOne(q){let s=50;s+=Math.max(-20,Math.min(20,num(q.pct_chg)||0)*2);const amount=num(q.amount)||0;s+=Math.min(15,Math.log10(Math.max(1,amount))-4);if((num(q.close)||0)>(num(q.pre_close)||Infinity))s+=5;return Math.round(Math.max(0,Math.min(100,s))*100)/100;}
function deepReview(stock,quote){const prices=stock?.prices||[],fs=stock?.statements?.[0],news=stock?.news||[],close=num(quote.close),avg20=prices.length?prices.reduce((a,p)=>a+num(p.close),0)/prices.length:null;const market={score:avg20?Math.max(0,Math.min(100,50+(close/avg20-1)*200)):50,view:avg20?(close>=avg20?'趋势偏强':'趋势偏弱'):'历史覆盖不足',evidence:prices.slice(0,3).map(p=>({type:'price',date:p.tradeDate,close:p.close,sourceUrl:p.sourceUrl}))};const roe=num(fs?.roe),fundamental={score:roe==null?50:Math.max(0,Math.min(100,50+(roe-8)*2)),view:roe==null?'财务覆盖不足':`最新 ROE ${roe}%`,evidence:fs?[{type:'financial',period:fs.periodEnd,roe:fs.roe,sourceUrl:fs.sourceUrl}]:[]};const sentiment=news.length?news.reduce((a,n)=>a+(num(n.sentiment)||0),0)/news.length:0,newsAgent={score:50+sentiment*40,view:news.length?`近期 ${news.length} 条新闻，平均情绪 ${sentiment.toFixed(2)}`:'新闻覆盖不足',evidence:news.slice(0,3).map(n=>({type:'news',title:n.title,url:n.url,publishedAt:n.publishedAt}))};const volatility=prices.length>2?Math.max(...prices.map(p=>num(p.high)||0))/Math.min(...prices.map(p=>num(p.low)||Infinity))-1:null,risk={score:volatility==null?50:Math.max(0,100-volatility*150),view:volatility==null?'风险历史覆盖不足':`近样本振幅 ${(volatility*100).toFixed(1)}%`,evidence:[]};return{agents:{market,fundamental,news:newsAgent,risk},deepScore:.3*market.score+.25*fundamental.score+.2*newsAgent.score+.25*risk.score,coverage:{history:prices.length,financial:fs?1:0,news:news.length}};}

export async function runFullMarketScan({trigger='manual'}={}){const db=getPrisma(),provider=new TushareProvider(),run=await db.marketScanRun.create({data:{provider:'tushare',trigger}}),degradation=[];try{const basics=await provider.stockBasic();if(basics.length<1000)throw Object.assign(new Error(`Tushare stock_basic returned only ${basics.length}; refusing to label it full market`),{code:'INCOMPLETE_UNIVERSE'});let quotes=[],tradeDate=null;for(let i=0;i<7&&!quotes.length;i++){const d=new Date(Date.now()-i*86400000);const rows=await provider.dailyQuotes({trade_date:dateKey(d)});if(rows.length){quotes=rows;tradeDate=rows[0].trade_date;}}const listed=new Set(basics.map(x=>x.ts_code)),matched=quotes.filter(x=>listed.has(x.ts_code));if(!quotes.length)throw Object.assign(new Error('No current Tushare all-market daily snapshot available'),{code:'SNAPSHOT_UNAVAILABLE'});const ratio=matched.length/basics.length;if(ratio<.85)throw Object.assign(new Error(`Snapshot covers only ${matched.length}/${basics.length}; refusing false full-market result`),{code:'INCOMPLETE_SNAPSHOT'});const first=matched.map(q=>({...q,stageOneScore:stageOne(q)})).sort((a,b)=>b.stageOneScore-a.stageOneScore),candidateRows=first.slice(0,Math.min(50,first.length)),codes=candidateRows.map(q=>q.ts_code.slice(0,6)),stocks=await db.stock.findMany({where:{code:{in:codes}},include:{prices:{take:60,orderBy:{tradeDate:'desc'}},statements:{take:1,orderBy:{periodEnd:'desc'}},news:{take:20,orderBy:{publishedAt:'desc'}}}}),byCode=new Map(stocks.map(s=>[s.code,s]));if(stocks.length<candidateRows.length)degradation.push({agent:'deep-review',reason:`${candidateRows.length-stocks.length} candidates absent from local evidence store; neutral evidence scores used`});const reviewed=candidateRows.map(q=>{const stock=byCode.get(q.ts_code.slice(0,6)),deep=deepReview(stock,q);return{code:q.ts_code.slice(0,6),tsCode:q.ts_code,name:stock?.name||basics.find(x=>x.ts_code===q.ts_code)?.name,quote:q,stageOneScore:q.stageOneScore,...deep,finalScore:.4*q.stageOneScore+.6*deep.deepScore};}).sort((a,b)=>b.finalScore-a.finalScore);const results=reviewed.slice(0,10);return await db.marketScanRun.update({where:{id:run.id},data:{tradeDate:new Date(`${tradeDate.slice(0,4)}-${tradeDate.slice(4,6)}-${tradeDate.slice(6,8)}T00:00:00Z`),status:degradation.length?'degraded':'succeeded',universeSize:basics.length,snapshotSize:quotes.length,coveredCount:matched.length,candidateCount:candidateRows.length,actualUniverse:{definition:'Tushare listed A-shares intersect same-day daily snapshot',listedCount:basics.length,snapshotCount:quotes.length,intersectionCount:matched.length,coverageRatio:ratio,tradeDate},degradation,results,finishedAt:new Date()}});}catch(error){await db.marketScanRun.update({where:{id:run.id},data:{status:'failed',degradation:[...degradation,{stage:'universe-or-snapshot',reason:error.message}],error:error.message,finishedAt:new Date()}});throw error;}}

function present(run){const universe=run.actualUniverse||{},items=(run.results||[]).map(item=>({...item,totalScore:item.finalScore,agents:Object.entries(item.agents||{}).map(([name,value])=>({name,score:value.score,view:value.view,evidence:value.evidence}))}));return{...run,items,coverage:{status:universe.coverageRatio>=.85?'full':'insufficient',isFullMarket:universe.coverageRatio>=.85,totalListed:run.universeSize,scannedCount:run.coveredCount,candidateCount:run.candidateCount,coverageRatio:universe.coverageRatio},scannedAt:run.finishedAt,dataAsOf:run.tradeDate,stage:'多 Agent 深度复核完成',method:{stages:['全市场基础列表','当日快照初筛','候选历史/财务/新闻/风险复核','Top10 排序']}};}
export const marketScanRouter=Router();
marketScanRouter.post('/market/top10/run',async(req,res,next)=>{try{const data=present(await runFullMarketScan({trigger:'manual'}));res.json({success:true,data,meta:{mock:false,fullMarket:data.coverage.isFullMarket}});}catch(e){next(e);}});
marketScanRouter.get('/market/top10/latest',async(_req,res,next)=>{try{const run=await getPrisma().marketScanRun.findFirst({where:{status:{in:['succeeded','degraded']}},orderBy:{startedAt:'desc'}});if(!run)throw Object.assign(new Error('尚无完成的全市场扫描'),{status:404,code:'SCAN_NOT_FOUND'});res.json({success:true,data:present(run),meta:{mock:false}});}catch(e){next(e);}});
marketScanRouter.post('/internal/scheduler/market-top10',async(req,res,next)=>{try{if(!process.env.MARKET_SCAN_SCHEDULER_TOKEN)throw Object.assign(new Error('MARKET_SCAN_SCHEDULER_TOKEN is not configured'),{status:503,code:'SCHEDULER_NOT_CONFIGURED'});if(req.get('x-scheduler-token')!==process.env.MARKET_SCAN_SCHEDULER_TOKEN)throw Object.assign(new Error('Invalid scheduler token'),{status:401,code:'INVALID_SCHEDULER_TOKEN'});res.json({success:true,data:await runFullMarketScan({trigger:'scheduler'})});}catch(e){next(e);}});
